// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EventBroker.EventTypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class CustomerCreated : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""CustomerCreated"",""namespace"":""EventBroker.EventTypes"",""fields"":[{""name"":""Id"",""doc"":""The id of the customer"",""type"":""long""},{""name"":""CreatedDate"",""doc"":""The date when the customer was created"",""type"":""long""},{""name"":""FirstName"",""doc"":""The first name of the customer"",""type"":""string""},{""name"":""LastName"",""doc"":""The last name of the customer"",""type"":""string""}]}");
		/// <summary>
		/// The id of the customer
		/// </summary>
		private long _Id;
		/// <summary>
		/// The date when the customer was created
		/// </summary>
		private long _CreatedDate;
		/// <summary>
		/// The first name of the customer
		/// </summary>
		private string _FirstName;
		/// <summary>
		/// The last name of the customer
		/// </summary>
		private string _LastName;
		public virtual Schema Schema
		{
			get
			{
				return CustomerCreated._SCHEMA;
			}
		}
		/// <summary>
		/// The id of the customer
		/// </summary>
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// The date when the customer was created
		/// </summary>
		public long CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				this._CreatedDate = value;
			}
		}
		/// <summary>
		/// The first name of the customer
		/// </summary>
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				this._FirstName = value;
			}
		}
		/// <summary>
		/// The last name of the customer
		/// </summary>
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				this._LastName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.CreatedDate;
			case 2: return this.FirstName;
			case 3: return this.LastName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Int64)fieldValue; break;
			case 1: this.CreatedDate = (System.Int64)fieldValue; break;
			case 2: this.FirstName = (System.String)fieldValue; break;
			case 3: this.LastName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
