// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EventBroker.EventTypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class EnvironmentCreated : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""EnvironmentCreated"",""namespace"":""EventBroker.EventTypes"",""fields"":[{""name"":""Id"",""doc"":""The id of the environment"",""type"":""long""},{""name"":""CustomerId"",""doc"":""The id of the customer environment belongs too"",""type"":""long""},{""name"":""CreatedDate"",""doc"":""The date when the environment was created"",""type"":""long""}]}");
		/// <summary>
		/// The id of the environment
		/// </summary>
		private long _Id;
		/// <summary>
		/// The id of the customer environment belongs too
		/// </summary>
		private long _CustomerId;
		/// <summary>
		/// The date when the environment was created
		/// </summary>
		private long _CreatedDate;
		public virtual Schema Schema
		{
			get
			{
				return EnvironmentCreated._SCHEMA;
			}
		}
		/// <summary>
		/// The id of the environment
		/// </summary>
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// The id of the customer environment belongs too
		/// </summary>
		public long CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				this._CustomerId = value;
			}
		}
		/// <summary>
		/// The date when the environment was created
		/// </summary>
		public long CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				this._CreatedDate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.CustomerId;
			case 2: return this.CreatedDate;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Int64)fieldValue; break;
			case 1: this.CustomerId = (System.Int64)fieldValue; break;
			case 2: this.CreatedDate = (System.Int64)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
