// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EventBroker.EventTypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class EnvironmentCreateFailed : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""EnvironmentCreateFailed"",""namespace"":""EventBroker.EventTypes"",""fields"":[{""name"":""CustomerId"",""doc"":""The id of the customer environment create failed for"",""type"":""long""},{""name"":""CreatedDate"",""doc"":""The date when the environment create failed"",""type"":""long""}]}");
		/// <summary>
		/// The id of the customer environment create failed for
		/// </summary>
		private long _CustomerId;
		/// <summary>
		/// The date when the environment create failed
		/// </summary>
		private long _CreatedDate;
		public virtual Schema Schema
		{
			get
			{
				return EnvironmentCreateFailed._SCHEMA;
			}
		}
		/// <summary>
		/// The id of the customer environment create failed for
		/// </summary>
		public long CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				this._CustomerId = value;
			}
		}
		/// <summary>
		/// The date when the environment create failed
		/// </summary>
		public long CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				this._CreatedDate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CustomerId;
			case 1: return this.CreatedDate;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CustomerId = (System.Int64)fieldValue; break;
			case 1: this.CreatedDate = (System.Int64)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
