version: "3.9"
services:
  mongo:
    image: mongo:3.2.11
    volumes:
      - /data/db/mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mydbname
      PGDATA: /data/db/postgres
